import { type Metadata } from 'next'
import {
    ClerkProvider,
} from '@clerk/nextjs'
import { Spline_Sans } from 'next/font/google'
import './../globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'

const splineSans = Spline_Sans({
    variable: '--font-spline-sans',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700']
})


export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={`${splineSans.variable}  antialiased`}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SidebarProvider>
                            <AppSidebar />

                            {/* <Navbar /> */}
                            <main>
                                <SidebarTrigger />
                                {children}
                            </main>
                        </SidebarProvider>
                        {/* <Footer /> */}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}